### ISSUE TITLE
V0.1 Taxonomy draft

### ISSUE THREAD

**Issue by deanwampler** [The-AI-Alliance/trust-safety-evals#7]
This can be incomplete, but can we have some progress to put on the website by December 6 (~1 year anniversary of the Alliance)?

**Comment by deanwampler** [comment]
I added to the 11/30 milestone (to keep to 2-week iterations), but 12/6 is fine for delivery. Maybe we draft the taxonomy by 11/30, then refine and publish by 12/6?

**Comment by deanwampler** [comment]
Can you guys put together a straw man proposal before Thanksgiving next week?

**Comment by deanwampler** [comment]
Maybe under src somewhere in this repo? Get @bnayahu to review

**Comment by jolson-ibm** [comment]
Done. Branch 7 created with `./src/taxonomy_llm_eval_tasks.json`

**Comment by deanwampler** [comment]
PR??

**Comment by deanwampler** [comment]
Done... It's on the website taxonomy page.
